---

- import_tasks: system.yml tags=rails_deploy
- import_tasks: database.yml tags=rails_deploy_setup
  when: rails_deploy_database_create
- import_tasks: deploy_keys.yml tags=rails_deploy_setup
- import_tasks: deploy.yml tags=rails_deploy
- import_tasks: local_facts.yml tags=rails_deploy
